name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.77.137.241 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh debian@51.77.137.241 '
            cd /home/debian/payetonkawa/PayeTonKawa && 
            rm -rf * && 
            git clone https://github.com/MSPR2-PayeTonKawa/PayeTonKawa.git . && 
            git checkout main
          '

      - name: Setup on server
        run: |
          ssh debian@51.77.137.241 '
            cd /home/debian/payetonkawa/PayeTonKawa && 
            sudo docker-compose down && 
            sudo docker-compose up -d
          '
      
      - name: Configure Nginx
        run: |
          ssh debian@51.77.137.241 "
          if [ ! -f /etc/nginx/sites-available/payetonkawa ]; then
            echo 'server {
                listen 80;
                server_name payetonkawa.ptitlu.dev;

                location / {
                    proxy_pass http://localhost:8001;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }

                location /products/ {
                    proxy_pass http://localhost:8002/;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }

                location /orders/ {
                    proxy_pass http://localhost:8003/;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }
            }' | sudo tee /etc/nginx/sites-available/payetonkawa
            
            sudo ln -sf /etc/nginx/sites-available/payetonkawa /etc/nginx/sites-enabled/
            sudo certbot --nginx -d payetonkawa.ptitlu.dev --non-interactive --agree-tos --email admin@ptitlu.dev
            sudo nginx -t && sudo systemctl reload nginx
          fi
          " 